env_name: Reach
robots: Sawyer
controller_type: JOINT_VELOCITY
robot_obs_keys:
  - robot0_joint_pos_cos
  - robot0_joint_pos_sin
obj_obs_keys:
  - target_to_robot0_eef_pos
lat_obs_dim: 4
lat_act_dim: 4
env_kwargs:
  horizon: 200
  table_full_size: [0.6, 0.6, 0.05]
num_episodes: 10
model_dir: logs/09.25.2025/23-37-55_Reach_Panda_JOINT_VELOCITY_Sawyer_JOINT_VELOCITY_align_cycle/models/step_0028000
seed: 42
render_camera: frontview